### ISSUE TITLE
2048.c 코드 vs실행시 문제점

### ISSUE THREAD

**Issue by dlwngud1230** [wogus3602/OpenSource#4]
코드가 리눅스 커널기반으로 짜여있어서 그런지 
VS에서 지원하지 않는 헤더파일과 함수들을 window에 맞게 변환하는 작업이
필요할 것으로 보인다.

**Comment by wogus3602** [comment]
못 찾겠습니다. 어제 하루종일 봤는데도..

**Comment by manduiscoming** [comment]
보드에서 색이 안나오는 문제만 해결하면 편해질것같은데
코드에서 \033[, snprintf 명령어들과 reset 변수, getColor 함수를 사용하는 것들을 모두 주석을 달았더니 색도 안보이고 숫자도 안보였습니다. 여기서 주석 달았던 부분에 차근차근히 visual studio용 색 넣는 코드를 넣어보며 색과 숫자를 입혀보면 좋을 것 같네요.

**Comment by manduiscoming** [comment]
> 보드에서 색이 안나오는 문제만 해결하면 편해질것같은데
> 코드에서 \033[, snprintf 명령어들과 reset 변수, getColor 함수를 사용하는 것들을 모두 주석을 달았더니 색도 안보이고 숫자도 안보였습니다. 여기서 주석 달았던 부분에 차근차근히 visual studio용 색 넣는 코드를 넣어보며 색과 숫자를 입혀보면 좋을 것 같네요.

**Comment by manduiscoming** [comment]
보드에서 색이 안나오는 문제만 해결하면 편해질것같은데
코드에서 \033[, snprintf 명령어들과 reset 변수, getColor 함수를 사용하는 것들을 모두 주석을 달았더니 색도 안보이고 숫자도 안보였습니다. 여기서 주석 달았던 부분에 차근차근히 visual studio용 색 넣는 코드를 넣어보며 색과 숫자를 입혀보면 좋을 것 같네요.
