### ISSUE TITLE
처음에 가져온 코드에서 /033, snprintf 명령어와 기타 궁금증이 안풀리는 것들

### ISSUE THREAD

**Issue by manduiscoming** [wogus3602/OpenSource#7]
/033 과 snprintf 명령어가 VS에서  컴파일 하면 다르게 나온다. VS로 출력은 되는데 이 것에서 색들이 안 입혀지는 것 같다.
printf("%*s%s%*s", t - t / 2, "", s, t / 2, ""); 이 부분에서 변수 s와 t값에 데이터 값이 이상하게 들어가는 것 같다. 이상한 문자가 나온다.

**Comment by wogus3602** [comment]
\033 은 해결 snprintf 에 대해서는 더 공부 해봐야할 것 같음
